### ISSUE TITLE
MongoClient opened before fork

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/document-store#104]
Ao executar a imagem docker da aplicação é possível ver as seguintes mensagens de log:

> webapp_1  | /usr/local/lib/python3.7/site-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
> webapp_1  |   "MongoClient opened before fork. Create MongoClient only "

Isto acontece pois estamos utilizando o _Gunicorn_ como servidor de aplicação que opera no modelo _pre-fork_ . O problema é que o pymongo não é _fork-safe_, como explicado no link da mensagem de log, portanto não deveria ser instanciado no _master process_.

**Comment by jamilatta** [comment]
@gustavofonseca 

Então teríamos que instância o Pymongo a cada requisição, por exemplo?

**Comment by gustavofonseca** [comment]
> @gustavofonseca
> 
> Então teríamos que instânciar o Pymongo a cada requisição, por exemplo?

Criar uma instância a cada requisição seria bastante ineficiente por conta da _connection pool_ do PyMongo. Dá uma lida em http://api.mongodb.com/python/current/faq.html#how-does-connection-pooling-work-in-pymongo

**Comment by gustavofonseca** [comment]
Resolvido
