### ISSUE TITLE
[Domain][Journal] Incluir campo para métricas

### ISSUE THREAD

**Issue by patymori** [scieloorg/document-store#15]
O `Journal` deve manter campo para as métricas do periódico. No site novo, elas são exibidas da seguinte forma:
<img width="351" alt="screen shot 2019-01-31 at 11 49 45" src="https://user-images.githubusercontent.com/18053487/52058447-95a7f500-254e-11e9-97cd-6d9b4d9087c6.png">

O valor a ser esperado do campo `metrica` é um dicionário onde sua chaves serão o nome da metrica o valor sera uma estrutura de dado flexível (`list`, `dict`, `string`) com os dados que sera usados pelas aplicação 

```python
{
    "scimago": {
        "url": "http://scimago.org"
        "title": "Scimago"
    },
    "google": {
        "total_h5": 10,
        "h5_median": 5,
        "h5_year": 2018
    },
    "scielo": "valor medio"
} 
```

**Comment by cesarbruschetta** [comment]
O valor a ser esperado do campo `metrica` é um dicionário onde sua chaves serão o nome da metrica o valor sera uma estrutura de dado flexível (`list`, `dict`, `string`) com os dados que sera usados pelas aplicação 

```python
{
    "scimago": {
        "url": "http://scimago.org"
        "title": "Scimago"
    },
    "google": {
        "total_h5": 10,
        "h5_median": 5,
        "h5_year": 2018
    },
    "scielo": "valor medio"
} 
```
