### ISSUE TITLE
Adicionar atributos ao DocumentsBundleSchema

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/document-store#171]
### Descrição da tarefa
É necessário adicionar os campos `publication_month` e `publication_season` ao Schema `DocumentsBundleSchema`. Ao tentar realizar o update de entidades `documentsbundle` o opac-airflow envia tais campos que nunca são atualizados na API do Kernel. 

https://github.com/scieloorg/document-store/blob/9f61dea49d44c8d5d9fc872e497016a3f08f0944/documentstore/restfulapi.py#L221-L224

### Subtarefas
N/A

### Considerações e notas

Dependencias: #170 #159

**Comment by jamilatta** [comment]
# Nova resolução

Em conversa com o time de desenvolvimento no dia 29/08/2019 ficou decidido que o campo `publication_season` não é adequado ao caso de uso do Kernel. O campo passará a ter a estrutura de um dicionário `publication_months = {"month": 1}` ou `publication_months = {"interval": [1, 2]}`.

O campo `publication_month` (no singular) deve ser removido em detrimento do uso do `publication_months`.

@cesarbruschetta @joffilyfe @robertatakenaka @patymori

**Comment by jamilatta** [comment]
@patymori @cesarbruschetta @robertatakenaka @joffilyfe 

Pessoal vcs acham que o campo publication_month deve ser um campo obrigatório.

**Comment by jamilatta** [comment]
Em conversa com a equipe reafirmamos que nenhum campo será obrigatório!

**Comment by jamilatta** [comment]
Conversando com a equipe novamente, definimos que: 

A chave **"interval"** deve ser alterado para **range**, pois, acreditamos que é mais aderente.

As chaves **range** e **month** devem ser mutuamente exclusivos, portanto na existência de **range** não é permitido ter **month** e vice versa.

Outro ponto que definimos é que a tupla do campo **range** deve obrigatoriamente existe o índice 0 e o índice 1, sendo que 0 representa o **start_month** e 1 representa **end_month**. 

Para realizar essa atividade é possível utilizar os validadores no **colander**, veja: https://docs.pylonsproject.org/projects/colander/en/latest/basics.html
