### ISSUE TITLE
API de mudanças

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/document-store#50]
Deverá retornar uma lista ordenada dos registros que sofreram mudanças. A 
ordenação será dada por meio do timestamp da aplicação. Apenas a versão mais
recente de cada registro é garantida de ser obtida, i.e., no caso de registros
atualizados e na sequência removidos a API poderá não mais fornecer os dados
no estado intermediário, antes da remoção.

Request:

`GET /changes HTTP/1.1`

Parâmetros:

  * **since (string)**: Inicia a lista de resultados na mudança imediatamente
  posterior ao timestamp informado. Por padrão retornará desde a primeira
  mudança.
  * **limit (number)**: Limita o total de resultados obtidos. Deve ser utilizado
  com o parâmetro `since` para iterar sobre os resultados de maneira paginada. 
  O valor padrão é 500.

Response:

```
{
  "since": "2018-08-05T23:02:29.392990Z",
  "limit": 500,
  "results": [
    {
      "timestamp": "2018-08-05T23:02:29.392990Z", 
      "id": "documents/0034-8910-rsp-48-2-0347"
    },
    {
      "timestamp": "2018-08-05T23:09:09.569312Z", 
      "id": "documents/0034-8910-rsp-48-2-0347",
      "deleted": true
    }
  ]
}
```

A resposta é um objeto JSON com 3 atributos: 

  * **since**: o valor do argumento de mesmo nome enviado na requisição. O valor padrão é uma string vazia;
  * **limit**: o valor do argumento de mesmo nome enviado na requisição. O valor padrão é 500;
  * **results**: um array que indica o recurso que sofreu a mudança. Note que, 
  exceto para o caso de remoção do registro, não há qualquer indicação sobre a 
  natureza da mudança (criação ou atualização), já que em ambos os casos
  é esperado que o cliente (re)obtenha o registro completo.

**Comment by gustavofonseca** [comment]
Exemplo de código que consumirá e API de mudanças em https://gist.github.com/gustavofonseca/363272c3745fa73ac32fe5ac673b783e

**Comment by robertatakenaka** [comment]
@gustavofonseca parece OK

**Comment by gustavofonseca** [comment]
O PR https://github.com/scieloorg/document-store/pull/76 contém todo o trabalho realizado para esta atividade até o momento.

**Comment by jamilatta** [comment]
Atividade realizada nos PRs: https://github.com/scieloorg/document-store/pull/95 e https://github.com/scieloorg/document-store/pull/76
