### ISSUE TITLE
[Domain][Journal] Compor com Documents Bundles por meio de adição

### ISSUE THREAD

**Issue by patymori** [scieloorg/document-store#55]
O `Journal` deve manter uma lista de bundles que o compõe por meio de adição nesta lista. O bundle é representado aqui pelo id e a adição deve ser ao final da lista.

Exemplo da lista:

```json
item = [
    "1",
    "2",
    "3",
]
```
Onde `1, 2` e `3` são ids de bundles.

**Comment by cesarbruschetta** [comment]
Relacionado ao Ticket #68
