### ISSUE TITLE
[Domain][Journal] Remoção de Documents Bundle 

### ISSUE THREAD

**Issue by patymori** [scieloorg/document-store#57]
O `Journal` deve permitir que um bundle seja retirado da lista de bundles que o compõe. O bundle é representado aqui pelo id.

Exemplo da lista:

```json
item = [
    "1",
    "2",
    "3",
]
```
Onde `1, 2` e `3` são ids de bundles.

**Comment by cesarbruschetta** [comment]
Relacionado ao ticket #68
