### ISSUE TITLE
[Services] Criar comandos para adicionar, inserir e remover fascículo em periódico

### ISSUE THREAD

**Issue by patymori** [scieloorg/document-store#70]
Deve existir comandos para adicionar, inserir e remover um fascículo em um periódico.

O comando adicionar deve receber o identificador do periódico e do fascículo, que deve ser adicionado ao final da lista de fascículos.

O comando inserir deve receber o identificador do periódico e do fascículo e a posição da lista onde  o fascículo deve ser inserido na lista de fascículos.

O comando remover deve receber o identificador do periódico e do fascículo, que deve ser removido da lista de fascículos.

**Comment by cesarbruschetta** [comment]
Branch #tk-70
7d8ba054f31f3d25f59f967b459dd6d2d01948cf
