### ISSUE TITLE
Restfull para a API de mudança.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/document-store#80]
Adicionar a capacidade de obtermos as mudanças que ocorreram nos registros do Kernel através de uma interface HTTP.

Request:

`GET /changes HTTP/1.1`

Parâmetros:

* **since (string)**: Inicia a lista de resultados na mudança imediatamente
  posterior ao timestamp informado. Por padrão retornará desde a primeira
  mudança.
* **limit (number)**: Limita o total de resultados obtidos. Deve ser utilizado
  com o parâmetro `since` para iterar sobre os resultados de maneira paginada.
  O valor padrão é 500.

Response:

```
{
  "last_timestamp": "2018-08-05T23:09:09.569312Z",
  "results": [
    {
      "timestamp": "2018-08-05T23:02:29.392990Z", 
      "id": "documents/0034-8910-rsp-48-2-0347"
    },
    {
      "timestamp": "2018-08-05T23:09:09.569312Z", 
      "id": "documents/0034-8910-rsp-48-2-0347",
      "deleted": true
    }
  ]
}
```
A resposta é um objeto JSON com 2 atributos:

* **last_timestamp**: que indica o timestamp da última mudança registrada;
* **results**: um array que indica o recurso que sofreu a mudança. Note que,
  exceto para o caso de remoção do registro, não há qualquer indicação sobre a
  natureza da mudança (criação ou atualização), já que em ambos os casos
  é esperado que o cliente (re)obtenha o registro completo.

**Comment by gustavofonseca** [comment]
Duplica o ticket #50
