### ISSUE TITLE
[Services] Criar comandos para set, get e remove de bundle de aop

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/document-store#87]
Deve existir comandos para set, get e remove de um "bundle" de artigos ahead of print.

O comando set deve receber o identificador do periódico e do fascículo.

O comando get deve receber o identificador do periódico.

O comando remover deve receber o identificador do periódico.

**Comment by jamilatta** [comment]
Atividade realizada no issue https://github.com/scieloorg/document-store/pull/93
